[package]
name = "lox-bytecode"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
itertools = "0.10.3"
num_enum = "0.5.6"
thiserror = "1.0.30"

[features]
print_code = []
trace_execution = []
